<?php

use Illuminate\Database\Seeder;

class AdminOperationLogTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('admin_operation_log')->delete();

        \DB::table('admin_operation_log')->insert(
            [
                0 =>
                    [
                        'id' => 1,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:47:38',
                        'updated_at' => '2020-01-27 10:47:38',
                    ],
                1 =>
                    [
                        'id' => 2,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:48:30',
                        'updated_at' => '2020-01-27 10:48:30',
                    ],
                2 =>
                    [
                        'id' => 3,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:48:41',
                        'updated_at' => '2020-01-27 10:48:41',
                    ],
                3 =>
                    [
                        'id' => 4,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"0","title":"\\u9996\\u9875","icon":"fa-bar-chart","uri":"\\/","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:49:00',
                        'updated_at' => '2020-01-27 10:49:00',
                    ],
                4 =>
                    [
                        'id' => 5,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:49:00',
                        'updated_at' => '2020-01-27 10:49:00',
                    ],
                5 =>
                    [
                        'id' => 6,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:13',
                        'updated_at' => '2020-01-27 10:49:13',
                    ],
                6 =>
                    [
                        'id' => 7,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:17',
                        'updated_at' => '2020-01-27 10:49:17',
                    ],
                7 =>
                    [
                        'id' => 8,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:21',
                        'updated_at' => '2020-01-27 10:49:21',
                    ],
                8 =>
                    [
                        'id' => 9,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:31',
                        'updated_at' => '2020-01-27 10:49:31',
                    ],
                9 =>
                    [
                        'id' => 10,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:34',
                        'updated_at' => '2020-01-27 10:49:34',
                    ],
                10 =>
                    [
                        'id' => 11,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:38',
                        'updated_at' => '2020-01-27 10:49:38',
                    ],
                11 =>
                    [
                        'id' => 12,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:39',
                        'updated_at' => '2020-01-27 10:49:39',
                    ],
                12 =>
                    [
                        'id' => 13,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:49:40',
                        'updated_at' => '2020-01-27 10:49:40',
                    ],
                13 =>
                    [
                        'id' => 14,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/1/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:46',
                        'updated_at' => '2020-01-27 10:49:46',
                    ],
                14 =>
                    [
                        'id' => 15,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:48',
                        'updated_at' => '2020-01-27 10:49:48',
                    ],
                15 =>
                    [
                        'id' => 16,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/2/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:49:56',
                        'updated_at' => '2020-01-27 10:49:56',
                    ],
                16 =>
                    [
                        'id' => 17,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/2',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"0","title":"\\u7cfb\\u7edf\\u7ba1\\u7406","icon":"fa-tasks","uri":null,"roles":["1",null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:50:05',
                        'updated_at' => '2020-01-27 10:50:05',
                    ],
                17 =>
                    [
                        'id' => 18,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:50:06',
                        'updated_at' => '2020-01-27 10:50:06',
                    ],
                18 =>
                    [
                        'id' => 19,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/3/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:08',
                        'updated_at' => '2020-01-27 10:50:08',
                    ],
                19 =>
                    [
                        'id' => 20,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/3',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"2","title":"\\u7528\\u6237\\u7ba1\\u7406","icon":"fa-users","uri":"auth\\/users","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:50:17',
                        'updated_at' => '2020-01-27 10:50:17',
                    ],
                20 =>
                    [
                        'id' => 21,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:50:17',
                        'updated_at' => '2020-01-27 10:50:17',
                    ],
                21 =>
                    [
                        'id' => 22,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/4/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:20',
                        'updated_at' => '2020-01-27 10:50:20',
                    ],
                22 =>
                    [
                        'id' => 23,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/4',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"2","title":"\\u89d2\\u8272\\u7ba1\\u7406","icon":"fa-user","uri":"auth\\/roles","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:50:27',
                        'updated_at' => '2020-01-27 10:50:27',
                    ],
                23 =>
                    [
                        'id' => 24,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:50:27',
                        'updated_at' => '2020-01-27 10:50:27',
                    ],
                24 =>
                    [
                        'id' => 25,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/4/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:30',
                        'updated_at' => '2020-01-27 10:50:30',
                    ],
                25 =>
                    [
                        'id' => 26,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:31',
                        'updated_at' => '2020-01-27 10:50:31',
                    ],
                26 =>
                    [
                        'id' => 27,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/5/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:33',
                        'updated_at' => '2020-01-27 10:50:33',
                    ],
                27 =>
                    [
                        'id' => 28,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/5',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"2","title":"\\u6743\\u9650\\u7ba1\\u7406","icon":"fa-ban","uri":"auth\\/permissions","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:50:39',
                        'updated_at' => '2020-01-27 10:50:39',
                    ],
                28 =>
                    [
                        'id' => 29,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:50:39',
                        'updated_at' => '2020-01-27 10:50:39',
                    ],
                29 =>
                    [
                        'id' => 30,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/6/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:43',
                        'updated_at' => '2020-01-27 10:50:43',
                    ],
                30 =>
                    [
                        'id' => 31,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/6',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"2","title":"\\u83dc\\u5355\\u7ba1\\u7406","icon":"fa-bars","uri":"auth\\/menu","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:50:50',
                        'updated_at' => '2020-01-27 10:50:50',
                    ],
                31 =>
                    [
                        'id' => 32,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:50:50',
                        'updated_at' => '2020-01-27 10:50:50',
                    ],
                32 =>
                    [
                        'id' => 33,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/7/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:50:53',
                        'updated_at' => '2020-01-27 10:50:53',
                    ],
                33 =>
                    [
                        'id' => 34,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/7',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"2","title":"\\u64cd\\u4f5c\\u65e5\\u5fd7","icon":"fa-history","uri":"auth\\/logs","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 10:51:00',
                        'updated_at' => '2020-01-27 10:51:00',
                    ],
                34 =>
                    [
                        'id' => 35,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:51:01',
                        'updated_at' => '2020-01-27 10:51:01',
                    ],
                35 =>
                    [
                        'id' => 36,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:04',
                        'updated_at' => '2020-01-27 10:51:04',
                    ],
                36 =>
                    [
                        'id' => 37,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:08',
                        'updated_at' => '2020-01-27 10:51:08',
                    ],
                37 =>
                    [
                        'id' => 38,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:09',
                        'updated_at' => '2020-01-27 10:51:09',
                    ],
                38 =>
                    [
                        'id' => 39,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:10',
                        'updated_at' => '2020-01-27 10:51:10',
                    ],
                39 =>
                    [
                        'id' => 40,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:11',
                        'updated_at' => '2020-01-27 10:51:11',
                    ],
                40 =>
                    [
                        'id' => 41,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:13',
                        'updated_at' => '2020-01-27 10:51:13',
                    ],
                41 =>
                    [
                        'id' => 42,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:51:17',
                        'updated_at' => '2020-01-27 10:51:17',
                    ],
                42 =>
                    [
                        'id' => 43,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:52:20',
                        'updated_at' => '2020-01-27 10:52:20',
                    ],
                43 =>
                    [
                        'id' => 44,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:23',
                        'updated_at' => '2020-01-27 10:52:23',
                    ],
                44 =>
                    [
                        'id' => 45,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:24',
                        'updated_at' => '2020-01-27 10:52:24',
                    ],
                45 =>
                    [
                        'id' => 46,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:25',
                        'updated_at' => '2020-01-27 10:52:25',
                    ],
                46 =>
                    [
                        'id' => 47,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:25',
                        'updated_at' => '2020-01-27 10:52:25',
                    ],
                47 =>
                    [
                        'id' => 48,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:28',
                        'updated_at' => '2020-01-27 10:52:28',
                    ],
                48 =>
                    [
                        'id' => 49,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:41',
                        'updated_at' => '2020-01-27 10:52:41',
                    ],
                49 =>
                    [
                        'id' => 50,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/2/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:48',
                        'updated_at' => '2020-01-27 10:52:48',
                    ],
                50 =>
                    [
                        'id' => 51,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:52:53',
                        'updated_at' => '2020-01-27 10:52:53',
                    ],
                51 =>
                    [
                        'id' => 52,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:53:02',
                        'updated_at' => '2020-01-27 10:53:02',
                    ],
                52 =>
                    [
                        'id' => 53,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 10:53:05',
                        'updated_at' => '2020-01-27 10:53:05',
                    ],
                53 =>
                    [
                        'id' => 54,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:53:06',
                        'updated_at' => '2020-01-27 10:53:06',
                    ],
                54 =>
                    [
                        'id' => 55,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:02',
                        'updated_at' => '2020-01-27 10:54:02',
                    ],
                55 =>
                    [
                        'id' => 56,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:05',
                        'updated_at' => '2020-01-27 10:54:05',
                    ],
                56 =>
                    [
                        'id' => 57,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:18',
                        'updated_at' => '2020-01-27 10:54:18',
                    ],
                57 =>
                    [
                        'id' => 58,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:20',
                        'updated_at' => '2020-01-27 10:54:20',
                    ],
                58 =>
                    [
                        'id' => 59,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:22',
                        'updated_at' => '2020-01-27 10:54:22',
                    ],
                59 =>
                    [
                        'id' => 60,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:23',
                        'updated_at' => '2020-01-27 10:54:23',
                    ],
                60 =>
                    [
                        'id' => 61,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:24',
                        'updated_at' => '2020-01-27 10:54:24',
                    ],
                61 =>
                    [
                        'id' => 62,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:25',
                        'updated_at' => '2020-01-27 10:54:25',
                    ],
                62 =>
                    [
                        'id' => 63,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:49',
                        'updated_at' => '2020-01-27 10:54:49',
                    ],
                63 =>
                    [
                        'id' => 64,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:50',
                        'updated_at' => '2020-01-27 10:54:50',
                    ],
                64 =>
                    [
                        'id' => 65,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:52',
                        'updated_at' => '2020-01-27 10:54:52',
                    ],
                65 =>
                    [
                        'id' => 66,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:54',
                        'updated_at' => '2020-01-27 10:54:54',
                    ],
                66 =>
                    [
                        'id' => 67,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 10:54:56',
                        'updated_at' => '2020-01-27 10:54:56',
                    ],
                67 =>
                    [
                        'id' => 68,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:21:34',
                        'updated_at' => '2020-01-27 11:21:34',
                    ],
                68 =>
                    [
                        'id' => 69,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:21:37',
                        'updated_at' => '2020-01-27 11:21:37',
                    ],
                69 =>
                    [
                        'id' => 70,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:21:39',
                        'updated_at' => '2020-01-27 11:21:39',
                    ],
                70 =>
                    [
                        'id' => 71,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:22:34',
                        'updated_at' => '2020-01-27 11:22:34',
                    ],
                71 =>
                    [
                        'id' => 72,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:22:41',
                        'updated_at' => '2020-01-27 11:22:41',
                    ],
                72 =>
                    [
                        'id' => 73,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:22:42',
                        'updated_at' => '2020-01-27 11:22:42',
                    ],
                73 =>
                    [
                        'id' => 74,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:22:44',
                        'updated_at' => '2020-01-27 11:22:44',
                    ],
                74 =>
                    [
                        'id' => 75,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:22:45',
                        'updated_at' => '2020-01-27 11:22:45',
                    ],
                75 =>
                    [
                        'id' => 76,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:22:48',
                        'updated_at' => '2020-01-27 11:22:48',
                    ],
                76 =>
                    [
                        'id' => 77,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:39:37',
                        'updated_at' => '2020-01-27 11:39:37',
                    ],
                77 =>
                    [
                        'id' => 78,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:39',
                        'updated_at' => '2020-01-27 11:39:39',
                    ],
                78 =>
                    [
                        'id' => 79,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:41',
                        'updated_at' => '2020-01-27 11:39:41',
                    ],
                79 =>
                    [
                        'id' => 80,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:43',
                        'updated_at' => '2020-01-27 11:39:43',
                    ],
                80 =>
                    [
                        'id' => 81,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:43',
                        'updated_at' => '2020-01-27 11:39:43',
                    ],
                81 =>
                    [
                        'id' => 82,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:45',
                        'updated_at' => '2020-01-27 11:39:45',
                    ],
                82 =>
                    [
                        'id' => 83,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:47',
                        'updated_at' => '2020-01-27 11:39:47',
                    ],
                83 =>
                    [
                        'id' => 84,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:39:49',
                        'updated_at' => '2020-01-27 11:39:49',
                    ],
                84 =>
                    [
                        'id' => 85,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:40:21',
                        'updated_at' => '2020-01-27 11:40:21',
                    ],
                85 =>
                    [
                        'id' => 86,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:40:23',
                        'updated_at' => '2020-01-27 11:40:23',
                    ],
                86 =>
                    [
                        'id' => 87,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:41:14',
                        'updated_at' => '2020-01-27 11:41:14',
                    ],
                87 =>
                    [
                        'id' => 88,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:41:18',
                        'updated_at' => '2020-01-27 11:41:18',
                    ],
                88 =>
                    [
                        'id' => 89,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:41:50',
                        'updated_at' => '2020-01-27 11:41:50',
                    ],
                89 =>
                    [
                        'id' => 90,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:49:33',
                        'updated_at' => '2020-01-27 11:49:33',
                    ],
                90 =>
                    [
                        'id' => 91,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:52:30',
                        'updated_at' => '2020-01-27 11:52:30',
                    ],
                91 =>
                    [
                        'id' => 92,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:53:04',
                        'updated_at' => '2020-01-27 11:53:04',
                    ],
                92 =>
                    [
                        'id' => 93,
                        'user_id' => 1,
                        'path' => 'admin/user',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:53:06',
                        'updated_at' => '2020-01-27 11:53:06',
                    ],
                93 =>
                    [
                        'id' => 94,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:54:15',
                        'updated_at' => '2020-01-27 11:54:15',
                    ],
                94 =>
                    [
                        'id' => 95,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'POST',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"0","title":"\\u7528\\u6237\\u7ba1\\u7406","icon":"fa-user","uri":"\\/users","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl"}',
                        'created_at' => '2020-01-27 11:54:47',
                        'updated_at' => '2020-01-27 11:54:47',
                    ],
                95 =>
                    [
                        'id' => 96,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:54:48',
                        'updated_at' => '2020-01-27 11:54:48',
                    ],
                96 =>
                    [
                        'id' => 97,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:54:52',
                        'updated_at' => '2020-01-27 11:54:52',
                    ],
                97 =>
                    [
                        'id' => 98,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:54:58',
                        'updated_at' => '2020-01-27 11:54:58',
                    ],
                98 =>
                    [
                        'id' => 99,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:00',
                        'updated_at' => '2020-01-27 11:55:00',
                    ],
                99 =>
                    [
                        'id' => 100,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:00',
                        'updated_at' => '2020-01-27 11:55:00',
                    ],
                100 =>
                    [
                        'id' => 101,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:55:01',
                        'updated_at' => '2020-01-27 11:55:01',
                    ],
                101 =>
                    [
                        'id' => 102,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:55:04',
                        'updated_at' => '2020-01-27 11:55:04',
                    ],
                102 =>
                    [
                        'id' => 103,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:06',
                        'updated_at' => '2020-01-27 11:55:06',
                    ],
                103 =>
                    [
                        'id' => 104,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:07',
                        'updated_at' => '2020-01-27 11:55:07',
                    ],
                104 =>
                    [
                        'id' => 105,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:12',
                        'updated_at' => '2020-01-27 11:55:12',
                    ],
                105 =>
                    [
                        'id' => 106,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:16',
                        'updated_at' => '2020-01-27 11:55:16',
                    ],
                106 =>
                    [
                        'id' => 107,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:22',
                        'updated_at' => '2020-01-27 11:55:22',
                    ],
                107 =>
                    [
                        'id' => 108,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/8/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:55:26',
                        'updated_at' => '2020-01-27 11:55:26',
                    ],
                108 =>
                    [
                        'id' => 109,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/8',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"0","title":"\\u4f1a\\u5458\\u7ba1\\u7406","icon":"fa-user","uri":"\\/users","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 11:55:32',
                        'updated_at' => '2020-01-27 11:55:32',
                    ],
                109 =>
                    [
                        'id' => 110,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:55:33',
                        'updated_at' => '2020-01-27 11:55:33',
                    ],
                110 =>
                    [
                        'id' => 111,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/8/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:56:00',
                        'updated_at' => '2020-01-27 11:56:00',
                    ],
                111 =>
                    [
                        'id' => 112,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/8',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"0","title":"\\u7528\\u6237\\u7ba1\\u7406","icon":"fa-user","uri":"\\/users","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 11:56:06',
                        'updated_at' => '2020-01-27 11:56:06',
                    ],
                112 =>
                    [
                        'id' => 113,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:56:06',
                        'updated_at' => '2020-01-27 11:56:06',
                    ],
                113 =>
                    [
                        'id' => 114,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/3/edit',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:56:09',
                        'updated_at' => '2020-01-27 11:56:09',
                    ],
                114 =>
                    [
                        'id' => 115,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu/3',
                        'method' => 'PUT',
                        'ip' => '192.168.10.1',
                        'input' => '{"parent_id":"2","title":"\\u540e\\u53f0\\u7528\\u6237\\u7ba1\\u7406","icon":"fa-users","uri":"auth\\/users","roles":[null],"permission":null,"_token":"TGX28HyGXBkpmlPfpXQ8vXCoMuGIvhFaIteUhBwl","_method":"PUT","_previous_":"http:\\/\\/laravel-admin-skeleton.test\\/admin\\/auth\\/menu"}',
                        'created_at' => '2020-01-27 11:56:29',
                        'updated_at' => '2020-01-27 11:56:29',
                    ],
                115 =>
                    [
                        'id' => 116,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 11:56:29',
                        'updated_at' => '2020-01-27 11:56:29',
                    ],
                116 =>
                    [
                        'id' => 117,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:56:53',
                        'updated_at' => '2020-01-27 11:56:53',
                    ],
                117 =>
                    [
                        'id' => 118,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 11:56:55',
                        'updated_at' => '2020-01-27 11:56:55',
                    ],
                118 =>
                    [
                        'id' => 119,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 12:14:23',
                        'updated_at' => '2020-01-27 12:14:23',
                    ],
                119 =>
                    [
                        'id' => 120,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:24',
                        'updated_at' => '2020-01-27 12:14:24',
                    ],
                120 =>
                    [
                        'id' => 121,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:24',
                        'updated_at' => '2020-01-27 12:14:24',
                    ],
                121 =>
                    [
                        'id' => 122,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:26',
                        'updated_at' => '2020-01-27 12:14:26',
                    ],
                122 =>
                    [
                        'id' => 123,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:27',
                        'updated_at' => '2020-01-27 12:14:27',
                    ],
                123 =>
                    [
                        'id' => 124,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:28',
                        'updated_at' => '2020-01-27 12:14:28',
                    ],
                124 =>
                    [
                        'id' => 125,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:28',
                        'updated_at' => '2020-01-27 12:14:28',
                    ],
                125 =>
                    [
                        'id' => 126,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:31',
                        'updated_at' => '2020-01-27 12:14:31',
                    ],
                126 =>
                    [
                        'id' => 127,
                        'user_id' => 1,
                        'path' => 'admin/auth/setting',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:38',
                        'updated_at' => '2020-01-27 12:14:38',
                    ],
                127 =>
                    [
                        'id' => 128,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:14:45',
                        'updated_at' => '2020-01-27 12:14:45',
                    ],
                128 =>
                    [
                        'id' => 129,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 12:14:50',
                        'updated_at' => '2020-01-27 12:14:50',
                    ],
                129 =>
                    [
                        'id' => 130,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:28',
                        'updated_at' => '2020-01-27 12:15:28',
                    ],
                130 =>
                    [
                        'id' => 131,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:31',
                        'updated_at' => '2020-01-27 12:15:31',
                    ],
                131 =>
                    [
                        'id' => 132,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:49',
                        'updated_at' => '2020-01-27 12:15:49',
                    ],
                132 =>
                    [
                        'id' => 133,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:51',
                        'updated_at' => '2020-01-27 12:15:51',
                    ],
                133 =>
                    [
                        'id' => 134,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:52',
                        'updated_at' => '2020-01-27 12:15:52',
                    ],
                134 =>
                    [
                        'id' => 135,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:53',
                        'updated_at' => '2020-01-27 12:15:53',
                    ],
                135 =>
                    [
                        'id' => 136,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:54',
                        'updated_at' => '2020-01-27 12:15:54',
                    ],
                136 =>
                    [
                        'id' => 137,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:55',
                        'updated_at' => '2020-01-27 12:15:55',
                    ],
                137 =>
                    [
                        'id' => 138,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:56',
                        'updated_at' => '2020-01-27 12:15:56',
                    ],
                138 =>
                    [
                        'id' => 139,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:56',
                        'updated_at' => '2020-01-27 12:15:56',
                    ],
                139 =>
                    [
                        'id' => 140,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:57',
                        'updated_at' => '2020-01-27 12:15:57',
                    ],
                140 =>
                    [
                        'id' => 141,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:15:59',
                        'updated_at' => '2020-01-27 12:15:59',
                    ],
                141 =>
                    [
                        'id' => 142,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:16:00',
                        'updated_at' => '2020-01-27 12:16:00',
                    ],
                142 =>
                    [
                        'id' => 143,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:16:01',
                        'updated_at' => '2020-01-27 12:16:01',
                    ],
                143 =>
                    [
                        'id' => 144,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:16:05',
                        'updated_at' => '2020-01-27 12:16:05',
                    ],
                144 =>
                    [
                        'id' => 145,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:16:07',
                        'updated_at' => '2020-01-27 12:16:07',
                    ],
                145 =>
                    [
                        'id' => 146,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:16:31',
                        'updated_at' => '2020-01-27 12:16:31',
                    ],
                146 =>
                    [
                        'id' => 147,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:05',
                        'updated_at' => '2020-01-27 12:18:05',
                    ],
                147 =>
                    [
                        'id' => 148,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:06',
                        'updated_at' => '2020-01-27 12:18:06',
                    ],
                148 =>
                    [
                        'id' => 149,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:07',
                        'updated_at' => '2020-01-27 12:18:07',
                    ],
                149 =>
                    [
                        'id' => 150,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:07',
                        'updated_at' => '2020-01-27 12:18:07',
                    ],
                150 =>
                    [
                        'id' => 151,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 12:18:16',
                        'updated_at' => '2020-01-27 12:18:16',
                    ],
                151 =>
                    [
                        'id' => 152,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 12:18:20',
                        'updated_at' => '2020-01-27 12:18:20',
                    ],
                152 =>
                    [
                        'id' => 153,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:23',
                        'updated_at' => '2020-01-27 12:18:23',
                    ],
                153 =>
                    [
                        'id' => 154,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:25',
                        'updated_at' => '2020-01-27 12:18:25',
                    ],
                154 =>
                    [
                        'id' => 155,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:25',
                        'updated_at' => '2020-01-27 12:18:25',
                    ],
                155 =>
                    [
                        'id' => 156,
                        'user_id' => 1,
                        'path' => 'admin/auth/menu',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:26',
                        'updated_at' => '2020-01-27 12:18:26',
                    ],
                156 =>
                    [
                        'id' => 157,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:30',
                        'updated_at' => '2020-01-27 12:18:30',
                    ],
                157 =>
                    [
                        'id' => 158,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:31',
                        'updated_at' => '2020-01-27 12:18:31',
                    ],
                158 =>
                    [
                        'id' => 159,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:32',
                        'updated_at' => '2020-01-27 12:18:32',
                    ],
                159 =>
                    [
                        'id' => 160,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:34',
                        'updated_at' => '2020-01-27 12:18:34',
                    ],
                160 =>
                    [
                        'id' => 161,
                        'user_id' => 1,
                        'path' => 'admin/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '[]',
                        'created_at' => '2020-01-27 12:18:35',
                        'updated_at' => '2020-01-27 12:18:35',
                    ],
                161 =>
                    [
                        'id' => 162,
                        'user_id' => 1,
                        'path' => 'admin',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:37',
                        'updated_at' => '2020-01-27 12:18:37',
                    ],
                162 =>
                    [
                        'id' => 163,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:39',
                        'updated_at' => '2020-01-27 12:18:39',
                    ],
                163 =>
                    [
                        'id' => 164,
                        'user_id' => 1,
                        'path' => 'admin/auth/users',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:41',
                        'updated_at' => '2020-01-27 12:18:41',
                    ],
                164 =>
                    [
                        'id' => 165,
                        'user_id' => 1,
                        'path' => 'admin/auth/roles',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:42',
                        'updated_at' => '2020-01-27 12:18:42',
                    ],
                165 =>
                    [
                        'id' => 166,
                        'user_id' => 1,
                        'path' => 'admin/auth/permissions',
                        'method' => 'GET',
                        'ip' => '192.168.10.1',
                        'input' => '{"_pjax":"#pjax-container"}',
                        'created_at' => '2020-01-27 12:18:43',
                        'updated_at' => '2020-01-27 12:18:43',
                    ],
            ]
        );
    }
}